'use client';

import React, { createContext, useContext, useEffect, useState } from 'react';

type Language = 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  pt: {
    // Header
    'header.login': 'Entrar',
    'header.signup': 'Criar Conta',
    'header.blogName': 'Kreulich Blog',
    'header.profile': 'Perfil',
    'header.myPosts': 'Meus Posts',
    'header.settings': 'Configurações',
    'header.logout': 'Sair',
    
    // Hero Section
    'hero.badge': '✨ Blog Pessoal',
    'hero.title': 'Compartilhando conhecimento e experiências',
    'hero.subtitle': 'Um espaço onde compartilho insights sobre tecnologia, desenvolvimento e experiências pessoais. Junte-se à comunidade e descubra conteúdo valioso.',
    'hero.exploreButton': 'Começar a Explorar',
    'hero.signupButton': 'Criar Minha Conta',
    
    // Features Section
    'features.title': 'Por que escolher este blog?',
    'features.subtitle': 'Conteúdo de qualidade, comunidade ativa e experiências reais compartilhadas',
    'features.exclusiveContent.title': 'Conteúdo Exclusivo',
    'features.exclusiveContent.description': 'Artigos únicos sobre tecnologia, desenvolvimento e experiências.',
    'features.community.title': 'Comunidade Ativa',
    'features.community.description': 'Conecte-se com outros desenvolvedores e compartilhe experiências',
    'features.updates.title': 'Atualizações Regulares',
    'features.updates.description': 'Novo conteúdo semanal com insights e tutoriais práticos',
    
    // Stats Section
    'stats.articles': 'Artigos Publicados',
    'stats.readers': 'Leitores Ativos',
    'stats.tutorials': 'Tutoriais Práticos',
    'stats.rating': 'Avaliação',
    
    // CTA Section
    'cta.title': 'Pronto para começar sua jornada?',
    'cta.subtitle': 'Junte-se à comunidade e tenha acesso a conteúdo exclusivo',
    'cta.signupButton': 'Criar Conta Gratuita',
    'cta.exploreButton': 'Explorar Blog',
    
    // Footer
    'footer.copyright': 'Todos os direitos reservados.',
    
    // 404 Page
    '404.title': 'Página não encontrada',
    '404.subtitle': 'Ops! Parece que você se perdeu.',
    '404.description': 'A página que você está procurando não existe ou foi movida.',
    '404.backHome': 'Voltar ao Início',
    '404.exploreBlog': 'Explorar Blog',
    
    // Layout/Meta
    'meta.title': 'Kreulich Blog',
    'meta.description': 'Blog sobre tecnologia, programação e outros assuntos.',
    
    // Cookie Consent
    'cookies.title': 'Política de Cookies',
    'cookies.subtitle': 'Sua privacidade é importante para nós',
    'cookies.description': 'Utilizamos cookies para melhorar sua experiência, analisar o tráfego do site e personalizar conteúdo. Ao continuar navegando, você concorda com nossa política de cookies.',
    'cookies.essential.title': 'Cookies Essenciais',
    'cookies.essential.description': 'Necessários para o funcionamento básico do site',
    'cookies.preferences.title': 'Cookies de Preferências',
    'cookies.preferences.description': 'Armazenam suas configurações de idioma e tema',
    'cookies.analytics.title': 'Cookies de Analytics',
    'cookies.analytics.description': 'Nos ajudam a entender como você usa o site',
    'cookies.marketing.title': 'Cookies de Marketing',
    'cookies.marketing.description': 'Usados para personalizar anúncios e conteúdo',
    'cookies.always': 'Sempre ativo',
    'cookies.optional': 'Opcional',
    'cookies.accept': 'Aceitar Todos',
    'cookies.decline': 'Recusar',
    'cookies.settings': 'Configurações',
    'cookies.acceptAll': 'Aceitar Todos',
    'cookies.declineAll': 'Recusar Todos',
    'cookies.cancel': 'Cancelar',
    'cookies.save': 'Salvar',
    'cookies.settingsDescription': 'Gerencie suas preferências de cookies. Você pode ativar ou desativar diferentes tipos de cookies conforme sua preferência.',
    'cookies.banner.text': 'Cookies configurados',
    'cookies.footer': 'Você pode alterar suas preferências a qualquer momento nas configurações.',
    
    // Sign In Page
    'signin.title': 'Bem-vindo de volta',
    'signin.subtitle': 'Entre com suas credenciais para acessar sua conta',
    'signin.email': 'E-mail',
    'signin.emailPlaceholder': 'seu@email.com',
    'signin.password': 'Senha',
    'signin.passwordPlaceholder': 'Digite sua senha',
    'signin.rememberMe': 'Lembrar de mim',
    'signin.forgotPassword': 'Esqueceu a senha?',
    'signin.loginButton': 'Entrar',
    'signin.or': 'ou',
    'signin.noAccount': 'Não tem uma conta?',
    'signin.createAccount': 'Criar conta',
    
    // Sign Up Page
    'signup.title': 'Criar sua conta',
    'signup.subtitle': 'Preencha os dados abaixo para começar sua jornada',
    'signup.fullName': 'Nome completo',
    'signup.fullNamePlaceholder': 'Digite seu nome completo',
    'signup.email': 'E-mail',
    'signup.emailPlaceholder': 'seu@email.com',
    'signup.password': 'Senha',
    'signup.passwordPlaceholder': 'Crie uma senha segura',
    'signup.jobRole': 'Cargo',
    'signup.jobRolePlaceholder': 'Selecione seu cargo',
    'signup.otherJobRole': 'Especifique o cargo',
    'signup.otherJobRolePlaceholder': 'Digite seu cargo',
    'signup.signupButton': 'Criar conta',
    'signup.or': 'ou',
    'signup.haveAccount': 'Já tem uma conta?',
    'signup.signIn': 'Fazer login',
    'signup.jobRoles.developer': 'Desenvolvedor',
    'signup.jobRoles.softwareEngineer': 'Engenheiro de Software',
    'signup.jobRoles.frontendDeveloper': 'Desenvolvedor Frontend',
    'signup.jobRoles.backendDeveloper': 'Desenvolvedor Backend',
    'signup.jobRoles.fullstackDeveloper': 'Desenvolvedor Full Stack',
    'signup.jobRoles.devopsEngineer': 'Engenheiro DevOps',
    'signup.jobRoles.dataScientist': 'Cientista de Dados',
    'signup.jobRoles.productManager': 'Product Manager',
    'signup.jobRoles.uiUxDesigner': 'UI/UX Designer',
    'signup.jobRoles.qaEngineer': 'Engenheiro QA',
    'signup.jobRoles.techLead': 'Tech Lead',
    'signup.jobRoles.other': 'Outro',
    
    // Blog Page
    'blog.highlights': 'Destaques',
    'blog.categories': 'Categorias',
    'blog.categoriesDescription': 'Explore nossos artigos organizados por categoria',
    'blog.allPosts': 'Todos os Artigos',
    'blog.allPostsDescription': 'Descubra todos os nossos artigos e tutoriais',
    'blog.readMore': 'Ler mais',
    'blog.loadMore': 'Carregar mais artigos',
    'blog.loading': 'Carregando...',
    'blog.noPosts': 'Nenhum post encontrado',
    'blog.noDescription': 'Sem descrição disponível',
    'blog.topWriters': 'Top Escritores',
    'blog.topWritersDescription': 'Os melhores escritores da comunidade, ranqueados por contribuições, engajamento e qualidade',
    'blog.completeRanking': 'Ranking Completo',
    'blog.online': 'Online',
    'blog.offline': 'Offline',
    'blog.posts': 'Posts',
    'blog.likes': 'Curtidas',
    'blog.comments': 'Comentários',
    'blog.views': 'Visualizações',
    'blog.points': 'pts',
    
    // Newsletter
    'newsletter.title': 'Receba nossas novidades',
    'newsletter.description': 'Inscreva-se em nossa newsletter e receba os melhores artigos diretamente no seu e-mail.',
    'newsletter.emailLabel': 'E-mail',
    'newsletter.emailPlaceholder': 'Digite seu e-mail',
    'newsletter.consentLabel': 'Autorizo o recebimento de e-mails',
    'newsletter.consentDescription': 'Você pode cancelar sua inscrição a qualquer momento.',
    'newsletter.subscribe': 'Inscrever-se',
    'newsletter.subscribing': 'Inscrevendo...',
    'newsletter.privacyNote': 'Respeitamos sua privacidade. Não compartilhamos seus dados com terceiros.',

    // Settings Page
    'settings.title': 'Configurações',
    'settings.subtitle': 'Gerencie suas informações pessoais e preferências',
    'settings.backToBlog': 'Voltar ao Blog',

    // Profile Page
    'profile.backToBlog': 'Voltar ao Blog',
    'profile.editProfile': 'Editar Perfil',
    'profile.memberSince': 'Membro desde',
    'profile.website': 'Website',
    'profile.stats.posts': 'Posts Publicados',
    'profile.stats.likes': 'Curtidas Recebidas',
    'profile.stats.comments': 'Comentários Feitos',
    'profile.tabs.posts': 'Posts',
    'profile.tabs.about': 'Sobre',
    'profile.noPosts': 'Nenhum post publicado',
    'profile.noPostsOwn': 'Você ainda não publicou nenhum post.',
    'profile.noPostsUser': 'Este usuário ainda não publicou nenhum post.',
    'profile.about.title': 'Sobre',
    'profile.about.description': 'Informações adicionais sobre o perfil',
    'profile.about.bio': 'Bio',
    'profile.about.role': 'Cargo',
    'profile.about.company': 'Empresa',
    'profile.about.location': 'Localização',
    'profile.about.joined': 'Entrou em',
    'profile.notFound': 'Usuário não encontrado',
    'profile.error': 'Erro ao carregar perfil',

    // My Posts Page
    'myPosts.title': 'Meus Posts',
    'myPosts.subtitle': 'Gerencie seus artigos e publicações',
    'myPosts.backToBlog': 'Voltar ao Blog',
    'myPosts.stats.total': 'Total de Posts',
    'myPosts.stats.published': 'Publicados',
    'myPosts.stats.draft': 'Rascunhos',
    'myPosts.filter.all': 'Todos',
    'myPosts.filter.published': 'Publicados',
    'myPosts.filter.draft': 'Rascunhos',
    'myPosts.search.placeholder': 'Buscar posts...',
    'myPosts.newPost': 'Novo Post',
    'myPosts.noPostsTitle': 'Nenhum post encontrado',
    'myPosts.noPostsAll': 'Você ainda não criou nenhum post.',
    'myPosts.noPostsPublished': 'Você não tem posts publicados.',
    'myPosts.noPostsDraft': 'Você não tem posts em rascunho.',
    'myPosts.createFirstPost': 'Criar Primeiro Post',
    'myPosts.badge.published': 'Publicado',
    'myPosts.badge.draft': 'Rascunho',
    'myPosts.badge.featured': 'Destaque',
    'myPosts.publishedAt': 'Publicado em',
    'myPosts.createdAt': 'Criado em',
    'myPosts.button.edit': 'Editar',
    'myPosts.delete.title': 'Tem certeza?',
    'myPosts.delete.description': 'Esta ação não pode ser desfeita. O post será permanentemente deletado.',
    'myPosts.delete.cancel': 'Cancelar',
    'myPosts.delete.confirm': 'Deletar',
    'myPosts.delete.deleting': 'Deletando...',
    'myPosts.toast.published': 'Post publicado',
    'myPosts.toast.unpublished': 'Post despublicado',
    'myPosts.toast.featured': 'Adicionado aos destaques',
    'myPosts.toast.unfeatured': 'Removido dos destaques',
    'myPosts.toast.deleted': 'Post deletado com sucesso',
    'myPosts.toast.error': 'Erro ao atualizar post',
    'myPosts.toast.loadError': 'Erro ao carregar posts',
    'settings.avatar.title': 'Foto de Perfil',
    'settings.avatar.description': 'Atualize sua foto de perfil. Máximo 5MB (JPEG, PNG ou WebP)',
    'settings.avatar.uploading': 'Enviando...',
    'settings.avatar.change': 'Alterar Foto',
    'settings.avatar.remove': 'Remover',
    'settings.profile.title': 'Informações do Perfil',
    'settings.profile.description': 'Atualize suas informações pessoais',
    'settings.profile.fullName': 'Nome Completo',
    'settings.profile.fullNamePlaceholder': 'Seu nome completo',
    'settings.profile.username': 'Nome de Usuário',
    'settings.profile.usernamePlaceholder': 'seu_username',
    'settings.profile.email': 'Email',
    'settings.profile.emailNote': 'O email não pode ser alterado',
    'settings.profile.bio': 'Bio',
    'settings.profile.bioPlaceholder': 'Conte um pouco sobre você...',
    'settings.profile.saving': 'Salvando...',
    'settings.profile.save': 'Salvar Alterações',
    'settings.password.title': 'Alterar Senha',
    'settings.password.description': 'Atualize sua senha para manter sua conta segura',
    'settings.password.current': 'Senha Atual',
    'settings.password.currentPlaceholder': 'Digite sua senha atual',
    'settings.password.new': 'Nova Senha',
    'settings.password.newPlaceholder': 'Digite sua nova senha',
    'settings.password.confirm': 'Confirmar Nova Senha',
    'settings.password.confirmPlaceholder': 'Confirme sua nova senha',
    'settings.password.changing': 'Alterando...',
    'settings.password.change': 'Alterar Senha',
    'settings.danger.title': 'Zona de Perigo',
    'settings.danger.description': 'Ações irreversíveis que afetam permanentemente sua conta',
    'settings.danger.deleteAccount': 'Excluir Conta',
    'settings.danger.deleteDescription': 'Uma vez excluída, sua conta não poderá ser recuperada. Todos os seus posts, comentários e dados serão permanentemente removidos.',
    'settings.danger.deleteButton': 'Excluir Minha Conta',
    'settings.danger.confirmTitle': 'Tem certeza absoluta?',
    'settings.danger.confirmDescription': 'Esta ação não pode ser desfeita. Isso irá excluir permanentemente sua conta e remover todos os seus dados dos nossos servidores.',
    'settings.danger.confirmIncludes': 'Isso inclui:',
    'settings.danger.confirmPosts': 'Todos os seus posts publicados',
    'settings.danger.confirmComments': 'Todos os seus comentários',
    'settings.danger.confirmLikes': 'Suas curtidas e interações',
    'settings.danger.confirmProfile': 'Sua foto de perfil e informações pessoais',
    'settings.danger.cancel': 'Cancelar',
    'settings.danger.deleting': 'Excluindo...',
    'settings.danger.confirmButton': 'Sim, excluir minha conta',

    // Admin Dashboard
    'admin.title': 'Painel Administrativo',
    'admin.subtitle': 'Gerencie todos os aspectos do seu blog',
    'admin.backToBlog': 'Voltar ao Blog',
    'admin.unauthorized': 'Acesso não autorizado',
    'admin.invalidHash': 'Hash inválida ou acesso negado',

    // Admin Tabs
    'admin.tabs.overview': 'Visão Geral',
    'admin.tabs.users': 'Usuários',
    'admin.tabs.posts': 'Posts',
    'admin.tabs.categories': 'Categorias',

    // Admin Overview
    'admin.overview.stats.users': 'Total de Usuários',
    'admin.overview.stats.posts': 'Total de Posts',
    'admin.overview.stats.categories': 'Categorias',
    'admin.overview.stats.comments': 'Comentários',
    'admin.overview.stats.likes': 'Curtidas',
    'admin.overview.topAuthors.title': 'Top Autores',
    'admin.overview.topAuthors.posts': 'posts',
    'admin.overview.topPosts.title': 'Posts Mais Curtidos',
    'admin.overview.topPosts.likes': 'curtidas',

    // Admin Users
    'admin.users.search': 'Buscar usuários...',
    'admin.users.table.avatar': 'Avatar',
    'admin.users.table.name': 'Nome',
    'admin.users.table.email': 'Email',
    'admin.users.table.role': 'Cargo',
    'admin.users.table.posts': 'Posts',
    'admin.users.table.createdAt': 'Criado em',
    'admin.users.table.actions': 'Ações',
    'admin.users.role.user': 'Usuário',
    'admin.users.role.writer': 'Escritor',
    'admin.users.role.editor': 'Editor',
    'admin.users.role.moderator': 'Moderador',
    'admin.users.role.admin': 'Admin',
    'admin.users.delete': 'Deletar',
    'admin.users.noUsers': 'Nenhum usuário encontrado',
    'admin.users.toast.roleUpdated': 'Cargo atualizado',
    'admin.users.toast.deleted': 'Usuário deletado',
    'admin.users.toast.error': 'Erro ao atualizar usuário',

    // Admin Posts
    'admin.posts.search': 'Buscar posts...',
    'admin.posts.table.title': 'Título',
    'admin.posts.table.author': 'Autor',
    'admin.posts.table.status': 'Status',
    'admin.posts.table.likes': 'Curtidas',
    'admin.posts.table.comments': 'Comentários',
    'admin.posts.table.createdAt': 'Criado em',
    'admin.posts.table.actions': 'Ações',
    'admin.posts.status.published': 'Publicado',
    'admin.posts.status.draft': 'Rascunho',
    'admin.posts.badge.featured': 'Destaque',
    'admin.posts.publish': 'Publicar',
    'admin.posts.unpublish': 'Despublicar',
    'admin.posts.feature': 'Destacar',
    'admin.posts.unfeature': 'Remover Destaque',
    'admin.posts.delete': 'Deletar',
    'admin.posts.noPosts': 'Nenhum post encontrado',
    'admin.posts.toast.published': 'Post publicado',
    'admin.posts.toast.unpublished': 'Post despublicado',
    'admin.posts.toast.featured': 'Adicionado aos destaques',
    'admin.posts.toast.unfeatured': 'Removido dos destaques',
    'admin.posts.toast.deleted': 'Post deletado',
    'admin.posts.toast.error': 'Erro ao atualizar post',

    // Admin Categories
    'admin.categories.newCategory': 'Nova Categoria',
    'admin.categories.cancelForm': 'Cancelar',
    'admin.categories.form.name': 'Nome',
    'admin.categories.form.namePlaceholder': 'Ex: Tecnologia',
    'admin.categories.form.slug': 'Slug',
    'admin.categories.form.slugPlaceholder': 'Ex: tecnologia',
    'admin.categories.form.description': 'Descrição',
    'admin.categories.form.descriptionPlaceholder': 'Descreva a categoria...',
    'admin.categories.form.color': 'Cor',
    'admin.categories.form.creating': 'Criando...',
    'admin.categories.form.create': 'Criar Categoria',
    'admin.categories.table.name': 'Nome',
    'admin.categories.table.slug': 'Slug',
    'admin.categories.table.posts': 'Posts',
    'admin.categories.table.color': 'Cor',
    'admin.categories.table.actions': 'Ações',
    'admin.categories.delete': 'Deletar',
    'admin.categories.noCategories': 'Nenhuma categoria encontrada',
    'admin.categories.toast.created': 'Categoria criada',
    'admin.categories.toast.deleted': 'Categoria deletada',
    'admin.categories.toast.error': 'Erro ao gerenciar categoria',

    // Admin Delete Dialog
    'admin.delete.title': 'Confirmar Exclusão',
    'admin.delete.user': 'Tem certeza que deseja deletar este usuário?',
    'admin.delete.post': 'Tem certeza que deseja deletar este post?',
    'admin.delete.category': 'Tem certeza que deseja deletar esta categoria?',
    'admin.delete.warning': 'Esta ação não pode ser desfeita.',
    'admin.delete.cancel': 'Cancelar',
    'admin.delete.confirm': 'Deletar',
    'admin.delete.deleting': 'Deletando...',

    // Admin Logs
    'admin.logs.tab': 'Logs',
    'admin.logs.search': 'Buscar logs...',
    'admin.logs.level': 'Nível',
    'admin.logs.levelAll': 'Todos',
    'admin.logs.clearLogs': 'Limpar Logs',
    'admin.logs.table.level': 'Nível',
    'admin.logs.table.datetime': 'Data/Hora',
    'admin.logs.table.message': 'Mensagem',
    'admin.logs.table.source': 'Origem',
    'admin.logs.noLogs': 'Nenhum log encontrado',
    'admin.logs.viewContext': 'Ver contexto',
    'admin.logs.clearDialog.title': 'Limpar Logs',
    'admin.logs.clearDialog.description': 'Tem certeza que deseja limpar os logs? Esta ação não pode ser desfeita.',
    'admin.logs.clearDialog.cancel': 'Cancelar',
    'admin.logs.clearDialog.confirm': 'Limpar Logs',
    'admin.logs.clearDialog.clearing': 'Limpando...',
    'admin.logs.toast.cleared': 'log(s) deletado(s)',
    'admin.logs.toast.error': 'Erro ao limpar logs',
  },
  en: {
    // Header
    'header.login': 'Login',
    'header.signup': 'Sign Up',
    'header.blogName': 'Kreulich Blog',
    'header.profile': 'Profile',
    'header.myPosts': 'My Posts',
    'header.settings': 'Settings',
    'header.logout': 'Logout',
    
    // Hero Section
    'hero.badge': '✨ Personal Blog',
    'hero.title': 'Sharing knowledge and experiences',
    'hero.subtitle': 'A space where I share insights about technology, development and personal experiences. Join the community and discover valuable content.',
    'hero.exploreButton': 'Start Exploring',
    'hero.signupButton': 'Create My Account',
    
    // Features Section
    'features.title': 'Why choose this blog?',
    'features.subtitle': 'Quality content, active community and real shared experiences',
    'features.exclusiveContent.title': 'Exclusive Content',
    'features.exclusiveContent.description': 'Unique articles about technology, development and experiences.',
    'features.community.title': 'Active Community',
    'features.community.description': 'Connect with other developers and share experiences',
    'features.updates.title': 'Regular Updates',
    'features.updates.description': 'Weekly new content with insights and practical tutorials',
    
    // Stats Section
    'stats.articles': 'Published Articles',
    'stats.readers': 'Active Readers',
    'stats.tutorials': 'Practical Tutorials',
    'stats.rating': 'Rating',
    
    // CTA Section
    'cta.title': 'Ready to start your journey?',
    'cta.subtitle': 'Join the community and get access to exclusive content',
    'cta.signupButton': 'Create Free Account',
    'cta.exploreButton': 'Explore Blog',
    
    // Footer
    'footer.copyright': 'All rights reserved.',
    
    // 404 Page
    '404.title': 'Page not found',
    '404.subtitle': 'Oops! Looks like you got lost.',
    '404.description': 'The page you are looking for does not exist or has been moved.',
    '404.backHome': 'Back to Home',
    '404.exploreBlog': 'Explore Blog',
    
    // Layout/Meta
    'meta.title': 'Kreulich Blog',
    'meta.description': 'Blog about technology, programming and other topics.',
    
    // Cookie Consent
    'cookies.title': 'Cookie Policy',
    'cookies.subtitle': 'Your privacy is important to us',
    'cookies.description': 'We use cookies to improve your experience, analyze site traffic and personalize content. By continuing to browse, you agree to our cookie policy.',
    'cookies.essential.title': 'Essential Cookies',
    'cookies.essential.description': 'Necessary for basic site functionality',
    'cookies.preferences.title': 'Preference Cookies',
    'cookies.preferences.description': 'Store your language and theme settings',
    'cookies.analytics.title': 'Analytics Cookies',
    'cookies.analytics.description': 'Help us understand how you use the site',
    'cookies.marketing.title': 'Marketing Cookies',
    'cookies.marketing.description': 'Used to personalize ads and content',
    'cookies.always': 'Always active',
    'cookies.optional': 'Optional',
    'cookies.accept': 'Accept All',
    'cookies.decline': 'Decline',
    'cookies.settings': 'Settings',
    'cookies.acceptAll': 'Accept All',
    'cookies.declineAll': 'Decline All',
    'cookies.cancel': 'Cancel',
    'cookies.save': 'Save',
    'cookies.settingsDescription': 'Manage your cookie preferences. You can enable or disable different types of cookies according to your preference.',
    'cookies.banner.text': 'Cookies configured',
    'cookies.footer': 'You can change your preferences at any time in settings.',
    
    // Sign In Page
    'signin.title': 'Welcome back',
    'signin.subtitle': 'Enter your credentials to access your account',
    'signin.email': 'Email',
    'signin.emailPlaceholder': 'your@email.com',
    'signin.password': 'Password',
    'signin.passwordPlaceholder': 'Enter your password',
    'signin.rememberMe': 'Remember me',
    'signin.forgotPassword': 'Forgot password?',
    'signin.loginButton': 'Sign In',
    'signin.or': 'or',
    'signin.noAccount': "Don't have an account?",
    'signin.createAccount': 'Create account',
    
    // Sign Up Page
    'signup.title': 'Create your account',
    'signup.subtitle': 'Fill in the data below to start your journey',
    'signup.fullName': 'Full name',
    'signup.fullNamePlaceholder': 'Enter your full name',
    'signup.email': 'Email',
    'signup.emailPlaceholder': 'your@email.com',
    'signup.password': 'Password',
    'signup.passwordPlaceholder': 'Create a secure password',
    'signup.jobRole': 'Job role',
    'signup.jobRolePlaceholder': 'Select your job role',
    'signup.otherJobRole': 'Specify job role',
    'signup.otherJobRolePlaceholder': 'Enter your job role',
    'signup.signupButton': 'Create account',
    'signup.or': 'or',
    'signup.haveAccount': 'Already have an account?',
    'signup.signIn': 'Sign in',
    'signup.jobRoles.developer': 'Developer',
    'signup.jobRoles.softwareEngineer': 'Software Engineer',
    'signup.jobRoles.frontendDeveloper': 'Frontend Developer',
    'signup.jobRoles.backendDeveloper': 'Backend Developer',
    'signup.jobRoles.fullstackDeveloper': 'Full Stack Developer',
    'signup.jobRoles.devopsEngineer': 'DevOps Engineer',
    'signup.jobRoles.dataScientist': 'Data Scientist',
    'signup.jobRoles.productManager': 'Product Manager',
    'signup.jobRoles.uiUxDesigner': 'UI/UX Designer',
    'signup.jobRoles.qaEngineer': 'QA Engineer',
    'signup.jobRoles.techLead': 'Tech Lead',
    'signup.jobRoles.other': 'Other',
    
    // Blog Page
    'blog.highlights': 'Highlights',
    'blog.categories': 'Categories',
    'blog.categoriesDescription': 'Explore our articles organized by category',
    'blog.allPosts': 'All Articles',
    'blog.allPostsDescription': 'Discover all our articles and tutorials',
    'blog.readMore': 'Read more',
    'blog.loadMore': 'Load more articles',
    'blog.loading': 'Loading...',
    'blog.noPosts': 'No posts found',
    'blog.noDescription': 'No description available',
    'blog.topWriters': 'Top Writers',
    'blog.topWritersDescription': 'The best writers in the community, ranked by contributions, engagement and quality',
    'blog.completeRanking': 'Complete Ranking',
    'blog.online': 'Online',
    'blog.offline': 'Offline',
    'blog.posts': 'Posts',
    'blog.likes': 'Likes',
    'blog.comments': 'Comments',
    'blog.views': 'Views',
    'blog.points': 'pts',
    
    // Newsletter
    'newsletter.title': 'Get our updates',
    'newsletter.description': 'Subscribe to our newsletter and receive the best articles directly in your email.',
    'newsletter.emailLabel': 'Email',
    'newsletter.emailPlaceholder': 'Enter your email',
    'newsletter.consentLabel': 'I authorize receiving emails',
    'newsletter.consentDescription': 'You can unsubscribe at any time.',
    'newsletter.subscribe': 'Subscribe',
    'newsletter.subscribing': 'Subscribing...',
    'newsletter.privacyNote': 'We respect your privacy. We do not share your data with third parties.',

    // Settings Page
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your personal information and preferences',
    'settings.backToBlog': 'Back to Blog',

    // Profile Page
    'profile.backToBlog': 'Back to Blog',
    'profile.editProfile': 'Edit Profile',
    'profile.memberSince': 'Member since',
    'profile.website': 'Website',
    'profile.stats.posts': 'Published Posts',
    'profile.stats.likes': 'Likes Received',
    'profile.stats.comments': 'Comments Made',
    'profile.tabs.posts': 'Posts',
    'profile.tabs.about': 'About',
    'profile.noPosts': 'No posts published',
    'profile.noPostsOwn': "You haven't published any posts yet.",
    'profile.noPostsUser': "This user hasn't published any posts yet.",
    'profile.about.title': 'About',
    'profile.about.description': 'Additional profile information',
    'profile.about.bio': 'Bio',
    'profile.about.role': 'Role',
    'profile.about.company': 'Company',
    'profile.about.location': 'Location',
    'profile.about.joined': 'Joined',
    'profile.notFound': 'User not found',
    'profile.error': 'Error loading profile',

    // My Posts Page
    'myPosts.title': 'My Posts',
    'myPosts.subtitle': 'Manage your articles and publications',
    'myPosts.backToBlog': 'Back to Blog',
    'myPosts.stats.total': 'Total Posts',
    'myPosts.stats.published': 'Published',
    'myPosts.stats.draft': 'Drafts',
    'myPosts.filter.all': 'All',
    'myPosts.filter.published': 'Published',
    'myPosts.filter.draft': 'Drafts',
    'myPosts.search.placeholder': 'Search posts...',
    'myPosts.newPost': 'New Post',
    'myPosts.noPostsTitle': 'No posts found',
    'myPosts.noPostsAll': "You haven't created any posts yet.",
    'myPosts.noPostsPublished': 'You have no published posts.',
    'myPosts.noPostsDraft': 'You have no draft posts.',
    'myPosts.createFirstPost': 'Create First Post',
    'myPosts.badge.published': 'Published',
    'myPosts.badge.draft': 'Draft',
    'myPosts.badge.featured': 'Featured',
    'myPosts.publishedAt': 'Published on',
    'myPosts.createdAt': 'Created on',
    'myPosts.button.edit': 'Edit',
    'myPosts.delete.title': 'Are you sure?',
    'myPosts.delete.description': 'This action cannot be undone. The post will be permanently deleted.',
    'myPosts.delete.cancel': 'Cancel',
    'myPosts.delete.confirm': 'Delete',
    'myPosts.delete.deleting': 'Deleting...',
    'myPosts.toast.published': 'Post published',
    'myPosts.toast.unpublished': 'Post unpublished',
    'myPosts.toast.featured': 'Added to featured',
    'myPosts.toast.unfeatured': 'Removed from featured',
    'myPosts.toast.deleted': 'Post deleted successfully',
    'myPosts.toast.error': 'Error updating post',
    'myPosts.toast.loadError': 'Error loading posts',
    'settings.avatar.title': 'Profile Picture',
    'settings.avatar.description': 'Update your profile picture. Maximum 5MB (JPEG, PNG or WebP)',
    'settings.avatar.uploading': 'Uploading...',
    'settings.avatar.change': 'Change Photo',
    'settings.avatar.remove': 'Remove',
    'settings.profile.title': 'Profile Information',
    'settings.profile.description': 'Update your personal information',
    'settings.profile.fullName': 'Full Name',
    'settings.profile.fullNamePlaceholder': 'Your full name',
    'settings.profile.username': 'Username',
    'settings.profile.usernamePlaceholder': 'your_username',
    'settings.profile.email': 'Email',
    'settings.profile.emailNote': 'Email cannot be changed',
    'settings.profile.bio': 'Bio',
    'settings.profile.bioPlaceholder': 'Tell us a little about yourself...',
    'settings.profile.saving': 'Saving...',
    'settings.profile.save': 'Save Changes',
    'settings.password.title': 'Change Password',
    'settings.password.description': 'Update your password to keep your account secure',
    'settings.password.current': 'Current Password',
    'settings.password.currentPlaceholder': 'Enter your current password',
    'settings.password.new': 'New Password',
    'settings.password.newPlaceholder': 'Enter your new password',
    'settings.password.confirm': 'Confirm New Password',
    'settings.password.confirmPlaceholder': 'Confirm your new password',
    'settings.password.changing': 'Changing...',
    'settings.password.change': 'Change Password',
    'settings.danger.title': 'Danger Zone',
    'settings.danger.description': 'Irreversible actions that permanently affect your account',
    'settings.danger.deleteAccount': 'Delete Account',
    'settings.danger.deleteDescription': 'Once deleted, your account cannot be recovered. All your posts, comments and data will be permanently removed.',
    'settings.danger.deleteButton': 'Delete My Account',
    'settings.danger.confirmTitle': 'Are you absolutely sure?',
    'settings.danger.confirmDescription': 'This action cannot be undone. This will permanently delete your account and remove all your data from our servers.',
    'settings.danger.confirmIncludes': 'This includes:',
    'settings.danger.confirmPosts': 'All your published posts',
    'settings.danger.confirmComments': 'All your comments',
    'settings.danger.confirmLikes': 'Your likes and interactions',
    'settings.danger.confirmProfile': 'Your profile picture and personal information',
    'settings.danger.cancel': 'Cancel',
    'settings.danger.deleting': 'Deleting...',
    'settings.danger.confirmButton': 'Yes, delete my account',

    // Admin Dashboard
    'admin.title': 'Admin Dashboard',
    'admin.subtitle': 'Manage all aspects of your blog',
    'admin.backToBlog': 'Back to Blog',
    'admin.unauthorized': 'Unauthorized access',
    'admin.invalidHash': 'Invalid hash or access denied',

    // Admin Tabs
    'admin.tabs.overview': 'Overview',
    'admin.tabs.users': 'Users',
    'admin.tabs.posts': 'Posts',
    'admin.tabs.categories': 'Categories',

    // Admin Overview
    'admin.overview.stats.users': 'Total Users',
    'admin.overview.stats.posts': 'Total Posts',
    'admin.overview.stats.categories': 'Categories',
    'admin.overview.stats.comments': 'Comments',
    'admin.overview.stats.likes': 'Likes',
    'admin.overview.topAuthors.title': 'Top Authors',
    'admin.overview.topAuthors.posts': 'posts',
    'admin.overview.topPosts.title': 'Most Liked Posts',
    'admin.overview.topPosts.likes': 'likes',

    // Admin Users
    'admin.users.search': 'Search users...',
    'admin.users.table.avatar': 'Avatar',
    'admin.users.table.name': 'Name',
    'admin.users.table.email': 'Email',
    'admin.users.table.role': 'Role',
    'admin.users.table.posts': 'Posts',
    'admin.users.table.createdAt': 'Created at',
    'admin.users.table.actions': 'Actions',
    'admin.users.role.user': 'User',
    'admin.users.role.writer': 'Writer',
    'admin.users.role.editor': 'Editor',
    'admin.users.role.moderator': 'Moderator',
    'admin.users.role.admin': 'Admin',
    'admin.users.delete': 'Delete',
    'admin.users.noUsers': 'No users found',
    'admin.users.toast.roleUpdated': 'Role updated',
    'admin.users.toast.deleted': 'User deleted',
    'admin.users.toast.error': 'Error updating user',

    // Admin Posts
    'admin.posts.search': 'Search posts...',
    'admin.posts.table.title': 'Title',
    'admin.posts.table.author': 'Author',
    'admin.posts.table.status': 'Status',
    'admin.posts.table.likes': 'Likes',
    'admin.posts.table.comments': 'Comments',
    'admin.posts.table.createdAt': 'Created at',
    'admin.posts.table.actions': 'Actions',
    'admin.posts.status.published': 'Published',
    'admin.posts.status.draft': 'Draft',
    'admin.posts.badge.featured': 'Featured',
    'admin.posts.publish': 'Publish',
    'admin.posts.unpublish': 'Unpublish',
    'admin.posts.feature': 'Feature',
    'admin.posts.unfeature': 'Unfeature',
    'admin.posts.delete': 'Delete',
    'admin.posts.noPosts': 'No posts found',
    'admin.posts.toast.published': 'Post published',
    'admin.posts.toast.unpublished': 'Post unpublished',
    'admin.posts.toast.featured': 'Added to featured',
    'admin.posts.toast.unfeatured': 'Removed from featured',
    'admin.posts.toast.deleted': 'Post deleted',
    'admin.posts.toast.error': 'Error updating post',

    // Admin Categories
    'admin.categories.newCategory': 'New Category',
    'admin.categories.cancelForm': 'Cancel',
    'admin.categories.form.name': 'Name',
    'admin.categories.form.namePlaceholder': 'E.g: Technology',
    'admin.categories.form.slug': 'Slug',
    'admin.categories.form.slugPlaceholder': 'E.g: technology',
    'admin.categories.form.description': 'Description',
    'admin.categories.form.descriptionPlaceholder': 'Describe the category...',
    'admin.categories.form.color': 'Color',
    'admin.categories.form.creating': 'Creating...',
    'admin.categories.form.create': 'Create Category',
    'admin.categories.table.name': 'Name',
    'admin.categories.table.slug': 'Slug',
    'admin.categories.table.posts': 'Posts',
    'admin.categories.table.color': 'Color',
    'admin.categories.table.actions': 'Actions',
    'admin.categories.delete': 'Delete',
    'admin.categories.noCategories': 'No categories found',
    'admin.categories.toast.created': 'Category created',
    'admin.categories.toast.deleted': 'Category deleted',
    'admin.categories.toast.error': 'Error managing category',

    // Admin Delete Dialog
    'admin.delete.title': 'Confirm Deletion',
    'admin.delete.user': 'Are you sure you want to delete this user?',
    'admin.delete.post': 'Are you sure you want to delete this post?',
    'admin.delete.category': 'Are you sure you want to delete this category?',
    'admin.delete.warning': 'This action cannot be undone.',
    'admin.delete.cancel': 'Cancel',
    'admin.delete.confirm': 'Delete',
    'admin.delete.deleting': 'Deleting...',

    // Admin Logs
    'admin.logs.tab': 'Logs',
    'admin.logs.search': 'Search logs...',
    'admin.logs.level': 'Level',
    'admin.logs.levelAll': 'All',
    'admin.logs.clearLogs': 'Clear Logs',
    'admin.logs.table.level': 'Level',
    'admin.logs.table.datetime': 'Date/Time',
    'admin.logs.table.message': 'Message',
    'admin.logs.table.source': 'Source',
    'admin.logs.noLogs': 'No logs found',
    'admin.logs.viewContext': 'View context',
    'admin.logs.clearDialog.title': 'Clear Logs',
    'admin.logs.clearDialog.description': 'Are you sure you want to clear the logs? This action cannot be undone.',
    'admin.logs.clearDialog.cancel': 'Cancel',
    'admin.logs.clearDialog.confirm': 'Clear Logs',
    'admin.logs.clearDialog.clearing': 'Clearing...',
    'admin.logs.toast.cleared': 'log(s) deleted',
    'admin.logs.toast.error': 'Error clearing logs',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('pt');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'pt' || savedLanguage === 'en')) {
      setLanguageState(savedLanguage);
    } else {
      setLanguageState('pt');
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
